# Copyright (C) 2022 Daniel Mueller <deso@posteo.net>
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Build and test with cargo ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [1.57.0, stable]
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true
    - name: Build
      run: cargo build
    - if: ${{ matrix.rust != 'stable' }}
      name: Run tests
      run: cargo test -- --include-ignored
    - if: ${{ matrix.rust == 'stable' }}
      name: Run tests
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: latest
        args: -- --include-ignored
        out-type: Xml
    - if: ${{ matrix.rust == 'stable' }}
      name: Upload code coverage results
      uses: codecov/codecov-action@v3
      with:
        files: cobertura.xml
  clippy:
    name: Lint with clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.57.0
          components: clippy
          override: true
      - run: cargo clippy --no-deps --all-targets --all-features -- -A unknown_lints -D warnings
